"""Generate the frozen SAM v2 PUBLIC field map from the official master-extract mapping.

The public monthly extract is the `Public`-flagged subset of the 362-field master record,
re-sequenced. Column names are the EXACT dictionary field names through one deterministic slug
(no semantic renames). Validated this session: 142 fields, url@27, !end@142, vs live KIPPER.

Reads the xlsx from R2 landing; emits `sam_v2_public_field_map.{json,py}` beside this file.

    doppler run -p core-x -c prd -- uv run --no-project --with boto3 --with openpyxl \
        python3 pipelines/sam_gov/reference/build_field_map.py
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

BUCKET = "data-sink"
KEY = "landing/sam-gov/data-dictionary/entity-information/SAM_MASTER_EXTRACT_MAPPING_Feb2025.xlsx"
HERE = Path(__file__).parent
XLSX_LOCAL = "/tmp/SAM_MASTER_EXTRACT_MAPPING_Feb2025.xlsx"

# The spreadsheet's `Public` (col M) flag is incomplete: these 4 parent-EVS-source fields are
# blank-flagged yet present in the public extract (proven by !end landing at position 142).
PUBLIC_FLAG_GAP_MASTER_ORDERS = {343, 344, 345, 346}

# Documented column alias — the cross-stack join key. Everything else is exact-slug.
COLUMN_ALIASES = {"UNIQUE ENTITY ID": "uei"}


def _r2():
    import boto3
    from botocore.config import Config

    ep = os.environ.get("R2_ENDPOINT") or f"https://{os.environ['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com"
    cfg = Config(request_checksum_calculation="when_required",
                 response_checksum_validation="when_required")
    return boto3.client("s3", endpoint_url=ep, region_name="auto", config=cfg,
                        aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
                        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"])


def slug(name: str) -> str:
    """Deterministic faithful slug: lowercase, non-alphanumeric runs → single `_`, trim."""
    return re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")


def build() -> list[dict]:
    import openpyxl

    if not os.path.exists(XLSX_LOCAL):
        _r2().download_file(BUCKET, KEY, XLSX_LOCAL)
    ws = openpyxl.load_workbook(XLSX_LOCAL, read_only=True, data_only=True)["Data Element Mapping"]

    rows = []
    for r in ws.iter_rows(min_row=5, values_only=True):
        name, order = r[0], r[1]
        if name is None or order is None:
            continue
        try:
            mo = int(order)
        except (ValueError, TypeError):
            continue
        public = str(r[12]).strip().upper() == "X" if len(r) > 12 and r[12] is not None else False
        if not public and mo not in PUBLIC_FLAG_GAP_MASTER_ORDERS:
            continue
        dict_name = str(name).strip()
        rows.append({
            "master_order": mo,
            "dictionary_name": dict_name,
            "column_name": COLUMN_ALIASES.get(dict_name, slug(dict_name)),
            "datatype": str(r[2] or "").strip(),
            "data_format": str(r[3] or "").strip(),
            "max_len": str(r[4] or "").strip(),
        })

    rows.sort(key=lambda x: x["master_order"])
    return [{"pos": i, **row} for i, row in enumerate(rows, 1)]


def validate(fm: list[dict]) -> None:
    by_name = {f["dictionary_name"]: f["pos"] for f in fm}
    assert len(fm) == 142, f"expected 142 public fields, got {len(fm)}"
    assert by_name["UNIQUE ENTITY ID"] == 1, "UEI not at pos 1"
    assert by_name["ENTITY URL"] == 27, f"ENTITY URL at {by_name['ENTITY URL']}, expected 27"
    assert by_name["PRIMARY NAICS"] == 33, "PRIMARY NAICS not at 33"
    assert by_name["END OF RECORD INDICATOR"] == 142, "END OF RECORD not at 142"
    cols = [f["column_name"] for f in fm]
    assert len(cols) == len(set(cols)), "duplicate column names"
    print(f"validation OK — {len(fm)} fields, uei@1, url@27, naics@33, end@142, names unique")


def emit(fm: list[dict]) -> None:
    (HERE / "sam_v2_public_field_map.json").write_text(json.dumps(fm, indent=2) + "\n")
    py = [
        '"""FROZEN — SAM v2 PUBLIC monthly-extract field map (142 fields).',
        "",
        "Generated by build_field_map.py from SAM_MASTER_EXTRACT_MAPPING_Feb2025.xlsx and validated",
        "against live records. Column names are exact dictionary names (faithful slug); `uei` is the",
        "one documented alias for UNIQUE ENTITY ID. Do not hand-edit — re-run the generator.",
        '"""',
        "from __future__ import annotations",
        "",
        "PUBLIC_FIELD_MAP: list[dict] = [",
    ]
    for f in fm:
        py.append(
            f'    {{"pos": {f["pos"]}, "master_order": {f["master_order"]}, '
            f'"dictionary_name": {f["dictionary_name"]!r}, "column_name": {f["column_name"]!r}, '
            f'"datatype": {f["datatype"]!r}, "data_format": {f["data_format"]!r}, '
            f'"max_len": {f["max_len"]!r}}},'
        )
    py += [
        "]",
        "",
        "# pos (1-based) -> column_name, and name -> pos helpers",
        "COL_AT = {f['pos']: f['column_name'] for f in PUBLIC_FIELD_MAP}",
        "POS_OF = {f['dictionary_name']: f['pos'] for f in PUBLIC_FIELD_MAP}",
        "DATE_POSITIONS = [f['pos'] for f in PUBLIC_FIELD_MAP if f['data_format'].upper() == 'YYYYMMDD']",
        "",
    ]
    (HERE / "sam_v2_public_field_map.py").write_text("\n".join(py))
    print(f"wrote sam_v2_public_field_map.json + .py ({len(fm)} fields)")


if __name__ == "__main__":
    fm = build()
    validate(fm)
    emit(fm)
