#!/usr/bin/env bash
# PreToolUse hook — frozen-validator immutability guard (G5).
#
# Blocks Write / Edit / MultiEdit / NotebookEdit tool calls that target a
# validator.json file living inside a scope-status/<slug>/ subdirectory once
# that file's on-disk content already has a non-null "validator_frozen_at"
# field.  This is the autoresearch "immutable scoreboard" invariant from
# Karpathy's playbook: the validator's frozen verdict is the scoreboard; only
# the orchestrator-controlled Stage 2 may stamp it; nothing downstream may
# rewrite it.
#
# Receives {tool_name, tool_input: {file_path, ...}} on stdin.
# Exit 0 = allow.  Exit 2 with stderr = block (Claude sees the message).
#
# Fail-open: if jq is missing, stdin is malformed, or we cannot read the
# on-disk file for any reason, we allow the call rather than break unrelated
# tools.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/_lib-remediation.sh"

INPUT=$(cat)

# Parse tool_name + file_path out of the JSON payload.
PARSED=$(printf '%s' "$INPUT" | python3 -c "
import json, sys
try:
    d = json.loads(sys.stdin.read())
    name = d.get('tool_name', '') or ''
    fp = (d.get('tool_input') or {}).get('file_path', '') or ''
    print(name + '\t' + fp)
except Exception:
    print('\t')
" 2>/dev/null || printf '\t')

TOOL_NAME=${PARSED%%$'\t'*}
FILE_PATH=${PARSED#*$'\t'}

# Belt-and-suspenders — the matcher in settings.json should already restrict
# this to file-write tools.
case "$TOOL_NAME" in
    Write|Edit|MultiEdit|NotebookEdit) ;;
    *) exit 0 ;;
esac

[ -z "$FILE_PATH" ] && exit 0

# Only care about files named exactly "validator.json".
BASENAME=$(basename "$FILE_PATH")
[ "$BASENAME" = "validator.json" ] || exit 0

# Only care about paths matching */scope-status/<slug>/validator.json.
# The parent dirname must be a direct child of a directory named "scope-status".
PARENT=$(dirname "$FILE_PATH")
GRANDPARENT=$(dirname "$PARENT")
GRANDPARENT_BASENAME=$(basename "$GRANDPARENT")
[ "$GRANDPARENT_BASENAME" = "scope-status" ] || exit 0

# File must exist on disk before we can inspect it.
[ -f "$FILE_PATH" ] || exit 0

# Require jq for the frozen-at check; fail-open if missing.
command -v jq >/dev/null 2>&1 || exit 0

# Block only when validator_frozen_at is present and non-null in the on-disk
# content.  jq -e exits non-zero if the expression is false or null.
if jq -e '.validator_frozen_at != null' "$FILE_PATH" >/dev/null 2>&1; then
    emit_remediation \
        "validator.json is frozen post-handoff per G5 autoresearch invariant. The on-disk validator.json at ${FILE_PATH} already has a non-null validator_frozen_at timestamp, which marks the validator's verdict as the immutable scoreboard for this /scope cycle (Karpathy autoresearch invariant). Only the Stage 2 orchestrator-controlled validator may stamp this file; no downstream agent — Stage 3, deploy-verifier, or any other executor — may rewrite it." \
        "Do not edit this file. If the harness needs to change, kill the cycle and re-validate: ask the human operator to manually delete the frozen validator.json and re-run Stage 2." \
        "${FILE_PATH}"
    exit 2
fi

exit 0
