#!/usr/bin/env python3
"""Distill the medicare-archive recon JSON into a committed, human-readable evidence file.

The recon probe (``scripts/recon_medicare_archive.py``) emits a ~2.4 MB JSON to stdout —
ephemeral, not reviewable in-repo. This reads that JSON and emits the auditable evidence
the diagnostic + plan rest on: grand totals, schema-drift-by-year per series (the full
header listed once per distinct signature), and a per-zip physical inventory with every
data file's schema fingerprint. Markdown → stdout.

    # full chain (regenerate from R2, then distill to the committed artifact):
    doppler run -p core-x -c prd -- python3 scripts/recon_medicare_archive.py > /tmp/medicare_recon.json
    python3 scripts/recon_medicare_evidence.py /tmp/medicare_recon.json \
        > docs/reference/medicare_archive_recon_evidence.md

Read-only. Pure function of its JSON input — no network, no R2.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys


def sig(header: list[str]) -> str:
    return hashlib.md5("|".join(header).encode()).hexdigest()[:8]


def member_year(name: str) -> str:
    m = re.search(r"/(20\d{2})/", name) or re.search(r"_D(?:Y)?(\d{2})_", name)
    if not m:
        return "—"
    g = m.group(1)
    return g if len(g) == 4 else f"20{g}"


def primary(z: dict) -> dict:
    df = z.get("data_files") or []
    return df[0] if df else {}


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/medicare_recon.json"
    with open(path) as fh:
        d = json.load(fh)
    zips = d["zips"]
    out: list[str] = []
    w = out.append

    # ── header ──
    w("# CMS Medicare Archive — Recon Evidence (committed ground truth)\n")
    w("> Auditable evidence base for [`medicare_archive_diagnostic.md`](../medicare_archive_diagnostic.md) and "
      "[`plans/medicare_ingestion_plan.md`](../plans/medicare_ingestion_plan.md). Generated by "
      "`scripts/recon_medicare_evidence.py` from the output of `scripts/recon_medicare_archive.py` "
      "(read-only ZIP-central-directory + bounded 50-row peek of every member). Every drift / grain / topology "
      "claim in those documents traces to a row below — no claim rests on data outside this file.\n")
    w(f"**Source:** `s3://{d['bucket']}/{d['prefix']}`  ·  **{len(zips)} zips** "
      f"(+{len(d.get('non_zip', []))} non-zip).\n")

    # ── grand totals ──
    tc = sum(z.get("compressed_bytes", 0) for z in zips)
    tu = sum(z.get("uncompressed_total", 0) for z in zips)
    ndata = sum(sum(1 for m in z.get("members", []) if m["class"] == "data") for z in zips)
    ndoc = sum(sum(1 for m in z.get("members", []) if m["class"] in ("doc", "dictionary")) for z in zips)
    w("## Grand totals\n")
    w(f"- Compressed: **{tc/1e9:.2f} GB**  ·  uncompressed (logical): **{tu/1e9:.2f} GB**  "
      f"(≈ {tu/max(tc,1):.1f}× expansion)")
    w(f"- Data members (`.csv`): **{ndata}**  ·  documentation/dictionary members: **{ndoc}**\n")

    # ── group by family/subgrain ──
    groups: dict[tuple, list] = {}
    for z in zips:
        groups.setdefault((z.get("family"), z.get("subgrain")), []).append(z)

    # ── drift by year ──
    w("## Schema drift — column count by program year (per series)\n")
    w("Each row is one source series; each cell is the peeked column count for that program year. "
      "A change across the row is drift. Full headers (one per distinct signature) follow each series.\n")
    for (fam, sub), lst in sorted(groups.items(), key=lambda kv: (str(kv[0][0]), str(kv[0][1]))):
        per_year: dict[str, int] = {}
        sigs: dict[str, dict] = {}
        for z in lst:
            for p in z.get("data_files", []):
                if "header" not in p:
                    continue
                yr = member_year(p["name"])
                per_year[yr] = p["n_cols"]
                s = sig(p["header"])
                sigs.setdefault(s, {"ncols": p["n_cols"], "npi": p.get("npi_col"),
                                    "header": p["header"], "years": set()})
                sigs[s]["years"].add(yr)
        if not per_year:
            continue
        years = sorted(y for y in per_year if y != "—")
        cells = " ".join(f"{y}:{per_year[y]}" for y in years) or "—"
        drift = "DRIFT" if len({per_year[y] for y in years}) > 1 else "stable"
        w(f"### `{fam}/{sub}` — **{drift}**")
        w(f"`{cells}`")
        for s, g in sigs.items():
            yrs = sorted(y for y in g["years"] if y != "—")
            span = f"{yrs[0]}–{yrs[-1]}" if len(yrs) > 1 else (yrs[0] if yrs else "—")
            w(f"- sig `{s}` · **{g['ncols']} cols** · npi=`{g['npi']}` · years {span}")
            w(f"  - `{g['header']}`")
        w("")

    # ── per-zip inventory ──
    w("## Per-zip physical inventory\n")
    for z in sorted(zips, key=lambda z: z["name"]):
        mem = z.get("members", [])
        nd = sum(1 for m in mem if m["class"] == "data")
        ndc = sum(1 for m in mem if m["class"] in ("doc", "dictionary"))
        w(f"### `{z['name']}`")
        w(f"`{z.get('family')}/{z.get('subgrain')}` · compressed {z.get('compressed_bytes',0)/1e6:.0f} MB · "
          f"uncompressed {z.get('uncompressed_total',0)/1e9:.2f} GB · "
          f"{len(mem)} members ({nd} data / {ndc} doc) · zip64={z.get('zip64')}")
        if z.get("error"):
            w(f"- **error:** {z['error']}\n")
            continue
        for p in z.get("data_files", []):
            if "header" not in p:
                w(f"- data `{p.get('name','?').rsplit('/',1)[-1]}` — peek error: {p.get('error')}")
                continue
            nsus = len(p.get("summary_suspects") or [])
            w(f"- data `{p['name'].rsplit('/',1)[-1]}` · yr {member_year(p['name'])} · "
              f"{p['n_cols']} cols · npi=`{p.get('npi_col')}` · {p.get('delimiter')}/{p.get('encoding')} · "
              f"sig `{sig(p['header'])}` · summary_suspects={nsus} · grain: {p.get('grain')}")
        docs = [m for m in mem if m["class"] in ("doc", "dictionary")]
        if docs:
            w(f"- docs/dict ({len(docs)}): " + ", ".join(
                f"`{m['name'].rsplit('/',1)[-1]}`" for m in docs[:8])
              + (" …" if len(docs) > 8 else ""))
        w("")

    if d.get("non_zip"):
        w("## Non-zip objects\n")
        for nz in d["non_zip"]:
            w(f"- `{nz['name']}` ({nz['size']/1e3:.1f} KB)")

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
