"""Bake — EQUIPMENT_PRONE: the six equipment-prone buckets page. ONE BUTTON.

Partition rule (operator-ruled 2026-07-26): buckets are defined over the AWARD's
NAICS only (PSC carried, unused in v1). No 'Other' on the page — professional
services (54) and info/finance (51/52) are deliberately excluded; the page shows
what the six buckets cover and claims nothing else. Reassignments from the old remainder,
drawn at the 6-digit boundary where needed (rules test the FULL award NAICS6):
561210 facilities/base support -> transportation/base-ops; 22 utilities -> industrial;
532 equipment rental/leasing -> construction. The rest of 561/53 (janitorial, guards,
staffing, real estate) deliberately stays OFF the page.

Per bucket: active-book dollars + est. equipment dollars (per-combo NAICS ->
KLEMS -> reference/equipment_flowdown_factors, same method as every other card).
Rewrites the EQUIPMENT_PRONE block in gc-hq-new rehearsal.ts.

Run: doppler run -p core-x -c prd -- python3 scripts/demo_bakes/bake_equipment_prone.py
"""
from __future__ import annotations
import os, re
from collections import defaultdict
from _shared import q, klems_mapping, flowdown_factors

BUCKETS=[
 ("Aerospace, defense & space manufacturing", lambda n: n.startswith("3364")),
 ("Shipbuilding & marine",                    lambda n: n.startswith("3366")),
 ("Industrial & manufacturing operations",    lambda n: n[:2] in ("31","32","33") or n[:2]=="22"),
 ("Construction & civil infrastructure",      lambda n: n.startswith("23") or n.startswith("532")),
 ("Environmental, waste & site services",     lambda n: n.startswith("562")),
 ("Transportation, logistics & base operations", lambda n: n[:2] in ("48","49") or n.startswith("561210")),
]

def main():
    to_pc=klems_mapping(); F=flowdown_factors()
    rows=q("SELECT naics_code, sum(active_obligated) FROM combo_award_active_state GROUP BY 1")
    agg=defaultdict(lambda:[0.0,0.0]); covered=0.0; total=0.0
    for n,v in rows:
        v=v or 0; total+=v; ns=str(n or "")
        for name,fn in BUCKETS:
            if fn(ns):
                agg[name][0]+=v; agg[name][1]+=v*F.get(to_pc(ns),0.039); covered+=v
                break
    lines=[]
    for name,_ in BUCKETS:
        o,e=agg[name]
        lines.append(f'  {{ name: "{name}", usd_b: {o/1e9:.0f}, equip_b: {e/1e9:.1f} }},')
    block=("/** GENERATED by scripts/demo_bakes/bake_equipment_prone.py — six equipment-prone\n"
           " * buckets over award NAICS (no Other by design; 54/51/52 excluded). equip_b =\n"
           " * per-combo NAICS -> KLEMS -> equipment_flowdown_factors v1. Do not hand-edit. */\n"
           "export const EQUIPMENT_PRONE = [\n"+"\n".join(lines)+"\n];")
    print(block)
    print(f"-- covered ${covered/1e9:.1f}B of ${total/1e9:.1f}B ({covered/total*100:.0f}%)")
    app=os.environ.get("GC_HQ_APP", os.path.expanduser("~/Desktop/gc-hq-new"))
    tgt=os.path.join(app,"apps/platform-app/src/map/rehearsal.ts")
    s=open(tgt).read()
    if "export const EQUIPMENT_PRONE" in s:
        s=re.sub(r"/\*\* GENERATED by scripts/demo_bakes/bake_equipment_prone\.py.*?\nexport const EQUIPMENT_PRONE = \[.*?\n\];",
                 lambda m: block, s, flags=re.S)
    else:
        s=s.replace("/** #1.2B — the figures card: the shape of the active $2.4T. */",
                    block+"\n\n/** #1.2B — the figures card: the shape of the active $2.4T. */",1)
    open(tgt,"w").write(s)
    print("-- rewrote", tgt)

if __name__=="__main__": main()
